# config.ini

[wordpress]
url = https://freerideinvestor.com/wp-json/wp/v2
username = DaDudeKC
password = H9yb ZIQe 8SuQ P5o9 VDln AGEc
categories = ["AI", "Automation", "Investing"]
tags = ["Blog Automation", "AI Tools", "Investment Strategies"]
status = publish
#status = draft

[vector_db]
D:\Freerideinvestor\AutoBloggerApp\config\config.ini

index_file = vector_store.index
metadata_file = vector_metadata.json
dimension = 768
# Dimension of the embeddings from Sentence Transformers